name: Create Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  create-container-instance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Container Instance
      run: |
        az container create --resource-group RGR-ACR --name registryvanes --image registryvanes.azurecr.io/getting-started:v1.0 --cpu 1 --memory 1 --os-type Linux --azure-file-volume-account-name <storage_account_name> --azure-file-volume-account-key <storage_account_key> --azure-file-volume-share-name <file_share_name> --azure-file-volume-mount-path /mnt/azurefile
