name: Create Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  create-container-instance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Container Instance
      run: |
        az container create --resource-group RGR-ACR --name containeres --registry-username registryvanes --registry-password 32tLVS1YrrowEzt1LLPdqx2hB7mw0QkwTb3gTeixgp+ACRC3BU36 --image registryvanes.azurecr.io/getting-started:v1.0 --cpu 1 --memory 1 --os-type Linux
